### ISSUE TITLE
Support Java 16-ea

### ISSUE THREAD

**Issue by sormuras** [TNG/ArchUnit#409]
Follow-up from #230 

Using ArchUnit with Java 16-ea the following **warning** is produced:

```text
WARN  com.tngtech.archunit.core.importer.ClassFileProcessor - Error during import from jrt:/java.base/java/lang/Double.class, falling back to simple import
2020-08-09T08:53:33.8837041Z java.lang.IllegalArgumentException: Unsupported class file major version 60
2020-08-09T08:53:33.8841068Z 	at com.tngtech.archunit.thirdparty.org.objectweb.asm.ClassReader.<init>(ClassReader.java:196) ~[archunit-0.14.1.jar:0.14.1]
2020-08-09T08:53:33.8845990Z 	at com.tngtech.archunit.thirdparty.org.objectweb.asm.ClassReader.<init>(ClassReader.java:177) ~[archunit-0.14.1.jar:0.14.1]
2020-08-09T08:53:33.8849712Z 	at com.tngtech.archunit.thirdparty.org.objectweb.asm.ClassReader.<init>(ClassReader.java:163) ~[archunit-0.14.1.jar:0.14.1]
2020-08-09T08:53:33.8853743Z 	at com.tngtech.archunit.thirdparty.org.objectweb.asm.ClassReader.<init>(ClassReader.java:284) ~[archunit-0.14.1.jar:0.14.1]
2020-08-09T08:53:33.8857894Z 	at com.tngtech.archunit.core.importer.ClassFileProcessor$UriImporterOfProcessor.tryImport(ClassFileProcessor.java:186) ~[archunit-0.14.1.jar:0.14.1]
2020-08-09T08:53:33.8863460Z 	at com.tngtech.archunit.core.importer.resolvers.ClassResolverFromClasspath.tryResolve(ClassResolverFromClasspath.java:51) ~[archunit-0.14.1.jar:0.14.1]
2020-08-09T08:53:33.8868778Z 	at com.tngtech.archunit.core.importer.ImportedClasses.ensurePresent(ImportedClasses.java:60) ~[archunit-0.14.1.jar:0.14.1]
2020-08-09T08:53:33.8873732Z 	at com.tngtech.archunit.core.importer.ClassGraphCreator.ensureCallTargetsArePresent(ClassGraphCreator.java:116) ~[archunit-0.14.1.jar:0.14.1]
2020-08-09T08:53:33.8877964Z 	at com.tngtech.archunit.core.importer.ClassGraphCreator.complete(ClassGraphCreator.java:98) ~[archunit-0.14.1.jar:0.14.1]
2020-08-09T08:53:33.8882517Z 	at com.tngtech.archunit.core.importer.ClassFileProcessor.process(ClassFileProcessor.java:62) ~[archunit-0.14.1.jar:0.14.1]
2020-08-09T08:53:33.8889662Z 	at com.tngtech.archunit.core.importer.ClassFileImporter.importLocations(ClassFileImporter.java:336) ~[archunit-0.14.1.jar:0.14.1]
2020-08-09T08:53:33.8897044Z 	at com.tngtech.archunit.junit.ClassCache$CacheClassFileImporter.importClasses(ClassCache.java:121) ~[archunit-junit5-engine-0.14.1.jar:0.14.1]
2020-08-09T08:53:33.8936872Z 	at com.tngtech.archunit.junit.ClassCache$LazyJavaClasses.initialize(ClassCache.java:113) ~[archunit-junit5-engine-0.14.1.jar:0.14.1]
2020-08-09T08:53:33.8937872Z 	at com.tngtech.archunit.junit.ClassCache$LazyJavaClasses.get(ClassCache.java:102) ~[archunit-junit5-engine-0.14.1.jar:0.14.1]
2020-08-09T08:53:33.8938572Z 	at com.tngtech.archunit.junit.ClassCache.getClassesToAnalyzeFor(ClassCache.java:79) ~[archunit-junit5-engine-0.14.1.jar:0.14.1]
2020-08-09T08:53:33.8946068Z 	at com.tngtech.archunit.junit.ArchUnitTestDescriptor.lambda$createChildren$1(ArchUnitTestDescriptor.java:82) ~[archunit-junit5-engine-0.14.1.jar:0.14.1]
2020-08-09T08:53:33.8946618Z 	at com.tngtech.archunit.thirdparty.com.google.common.base.Suppliers$MemoizingSupplier.get(Suppliers.java:120) ~[archunit-0.14.1.jar:0.14.1]
2020-08-09T08:53:33.8947155Z 	at com.tngtech.archunit.junit.ArchUnitTestDescriptor$ArchUnitRuleDescriptor.execute(ArchUnitTestDescriptor.java:159) ~[archunit-junit5-engine-0.14.1.jar:0.14.1]
2020-08-09T08:53:33.8947688Z 	at com.tngtech.archunit.junit.ArchUnitTestDescriptor$ArchUnitRuleDescriptor.execute(ArchUnitTestDescriptor.java:142) ~[archunit-junit5-engine-0.14.1.jar:0.14.1]
2020-08-09T08:53:33.8948218Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139) ~[junit-platform-engine-1.7.0-SNAPSHOT.jar:1.7.0-SNAPSHOT]
```

https://github.com/junit-team/junit5/runs/963324482#step:7:678

An upgrade of the shadowed ASM library to version [9.0 beta](https://asm.ow2.io/versions.html) should prevent this warning being emitted.

**Comment by codecholeric** [comment]
Some tasks never end :wink: We'll make sure to include the latest ASM release into the next ArchUnit release, even though it's a `beta` :disappointed: I wonder if it would make sense to add some flag to switch to an externally supplied ASM for users who always want to run the latest JDK as soon as possible :thinking: 
Would you actually use such a feature? (independently of how feasible it is from an ASM API point of view, I have not looked into it)

**Comment by sormuras** [comment]
A "core-only" (no externals shadowed) module/distro of ArchUnit would do the trick w/o the need for an extra switch.

Related thread: https://mail-archives.apache.org/mod_mbox/lucene-dev/202001.mbox/%3C000001d5c648$d7eff570$87cfe050$@thetaphi.de%3E

**Comment by jqno** [comment]
I'm also interested in this. And I feel your pain, @codecholeric. EqualsVerifier has the same issue, every half year...

**Comment by codecholeric** [comment]
Yeah, I'm gonna release the current version ASAP with the upgraded ASM version. Was a little bumpier this time, because of some broken meta-data (see https://gitlab.ow2.org/asm/asm/-/issues/317920)
I am thinking about releasing a separate version with unshadowed ASM, but I'm a little afraid of the build/release complexity, as that is already quite high I feel :thinking: 
Anyway, the new ASM support is merged already, I just wanted to wrap up some other issues, but if I can't do it quickly I'll just release the current state. It already has quite some nice new features and this time I have really not released for a while :disappointed: I should probably release more often, no reason really to delay it so much, `master` is "releasable" at all time anyway :thinking:

**Comment by jqno** [comment]
I didn't mean to rush you. A release would be nice to clean up my build logs, but it can certainly wait. I'm just happy ArchUnit exists at all, it's great!

**Comment by codecholeric** [comment]
Yeah, no worries, it was my plan anyway :wink:

**Comment by codecholeric** [comment]
Should be resolved through #466, otherwise feel free to reopen. To keep things simple I haven't extended the build yet to release two different versions of the core, I'd rather try to release quicker and smaller first. This time was really not optimal, if we release more often, this is not such a big pain. Or at least always when there is a new ASM version. In the end master was always releasable, I just didn't do it somehow, so I would first try to improve this in the future, before I introduce a more complex build.

**Comment by sormuras** [comment]
Thanks!

Shall I re-open this or create a new issue for Java 17-ea? ;-)

https://github.com/junit-team/junit5/runs/1572595524#step:7:683

**Comment by sormuras** [comment]
Java 17-ea related ASM issue: https://gitlab.ow2.org/asm/asm/-/issues/317924

**Comment by codecholeric** [comment]
This is good enough I think, I'm just gonna watch ASM more regularly and do a timely release as soon as new versions of ASM are released :wink: At least that's an attempt for now, let's see how well it works to have a closer related release cycle. If it doesn't work well for some reason I'm gonna look into splitting the release artifacts in one with and one without shadowed ASM...

**Comment by kerkhofsd** [comment]
Still experiencing WARNING's using `archunit-junit5` version `0.22.0`:

```
[WARNING] Couldn't import class from {}.class
java.lang.IllegalArgumentException: Unsupported class file major version 61
    at com.tngtech.archunit.thirdparty.org.objectweb.asm.ClassReader.<init> (ClassReader.java:189)
    at com.tngtech.archunit.thirdparty.org.objectweb.asm.ClassReader.<init> (ClassReader.java:170)
    at com.tngtech.archunit.thirdparty.org.objectweb.asm.ClassReader.<init> (ClassReader.java:156)
    at com.tngtech.archunit.thirdparty.org.objectweb.asm.ClassReader.<init> (ClassReader.java:277)
    at com.tngtech.archunit.core.importer.ClassFileProcessor.process (ClassFileProcessor.java:57)
```

Is that possible? 
Any expected release with bumped ASM version?

**Comment by hankem** [comment]
Hm, interesting: [ArchUnit 0.22.0 uses ASM 9.2](https://github.com/TNG/ArchUnit/blob/v0.22.0/build.gradle#L36), which is the most recent [ASM version](https://asm.ow2.io/versions.html) available. Can you share your class file?

**Comment by jqno** [comment]
I can confirm that version 0.22.0 works for me just fine on JDK 17 and even 18-ea.

**Comment by kerkhofsd** [comment]
It seems we were transitively using an older version of ArchUnit after all. 

Apologies for the confusion and thanks a lot for the feedback!

**Comment by hankem** [comment]
No worries! Glad that the issue could be resolved.
